ktor {
    deployment {
        port = 5132
        port = ${?PORT}
    }
    application {
        modules = [ com.wikilive.ApplicationKt.module ]
    }
}

db {
    url = "jdbc:postgresql://localhost:5432/wiki"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "06"
    password = ${?DB_PASSWORD}
}
